config/routes.rb
Rails.application.routes.draw do
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :registrations, only: %i[new create], path: 'sign_up', path_names: { new: '' }
  resources :events do
    resource :subscribers, only: %i[create destroy]
    resources :comments
  end
  resources :users, only: %i[index destroy] do
    put :promote, on: :member
    put :switch_activation, on: :member
  end
  resource :users, only: [] do
    get :events
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'events#index'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Everybody has obsessions - ours are events.</a>
  </small>
  <nav>
    <ul>
      <li>&copy; <%= Date.today.year %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to ("<i class='fa fa-calendar-check-o'></i> " + 'EVENTaholic').html_safe, root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= ('<i class="fa fa-user-circle"></i> ' + truncate(current_user.full_name, length: 25)).html_safe %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "<i class='fa fa-calendar-plus-o'></i> Add event".html_safe, new_event_path %></li>
              <li><%= link_to "<i class='fa fa-calendar-o'></i> Subscribed events".html_safe, events_users_path %></li>
              <% if current_user.is_admin %>
                <li><%= link_to "<i class='fa fa-cog'></i> Manage users".html_safe, users_path %></li>
              <% end %>
              <li><%= link_to "<i class='fa fa-power-off'></i> Log out".html_safe, logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "<i class='fa fa-lock'></i> Log in".html_safe, login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'shared/flash_messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

<%= debug(params) if Rails.env.development?%>